name: flutter_fbx3d_viewer
description: Flutter package for viewing Fbx 3d animated files with textures, basic lights, colors.
version: 1.0.1
homepage: https://github.com/oengmengthong/Flutter-FBX-3D-Viewer

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  vector_math: ^2.1.4
  archive: ^3.3.7
  image: ^4.0.17
  provider: ^6.0.5

  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
    #assets:
    #- assets/knight.fbx

